enum AuthWithGoogleTypes {
  AUTH_WITH_GOOGLE_START = "AUTH_WITH_GOOGLE_START",
  AUTH_WITH_GOOGLE_SUCCESS = "AUTH_WITH_GOOGLE_SUCCESS",
  AUTH_WITH_GOOGLE_FAILD = "AUTH_WITH_GOOGLE_FAILD",
}

enum AuthWithFacebookTypes {
  AUTH_WITH_FACEBOOK_START = "AUTH_WITH_FACEBOOK_START",
  AUTH_WITH_FACEBOOK_SUCCESS = "AUTH_WITH_FACEBOOK_SUCCESS",
  AUTH_WITH_FACEBOOK_FAILD = "AUTH_WITH_FACEBOOK_FAILD",
}

enum LoadUserTypes {
  LOAD_USER_START = "LOAD_USER_START",
  LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS",
  LOAD_USER_FAILD = "LOAD_USER_FAILD",
}

enum CheckAuthStatusTypes {
  CHECK_AUTH_STATUS_START = "CHECK_AUTH_STATUS_START",
  CHECK_AUTH_STATUS_SUCCESS = "CHECK_AUTH_STATUS_SUCCESS",
  CHECK_AUTH_STATUS_FAILD = "CHECK_AUTH_STATUS_FAILD",
}

enum RefreshTokenTypes {
  REFRESH_TOKEN_START = "REFRESH_TOKEN_START",
  REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS",
  REFRESH_TOKEN_FAILD = "REFRESH_TOKEN_FAILD",
}

enum LogoutTypes {
  LOGOUT_START = "LOGOUT_START",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAILD = "LOGOUT_FAILD",
}

export {
  AuthWithGoogleTypes,
  AuthWithFacebookTypes,
  LoadUserTypes,
  CheckAuthStatusTypes,
  RefreshTokenTypes,
  LogoutTypes,
};
